config/routes.rb
# -*- encoding : utf-8 -*-

LiberdadeEconomica::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  match '/delayed_job' => DelayedJobWeb, anchor: false

  # 1. user routes
  devise_for :users

  # 2. contact routes
  get '/contact' => 'site#contact', as: :contact
  post '/contact' => 'site#send_contact', as: :send_contact

  get '/ranking/:edition' => 'site#ranking', as: :ranking
  get '/pais/:name' => 'site#country', as: :country
  get '/dados' => 'site#data', as: :data
  get '/grafico/:category(/:country_1(/:country_2))' => 'site#graph', as: :graph
  get '/grafico_geral/:category' => 'site#general_graph', as: :general_graph
  get '/comparar/:name1/:name2' => 'site#comparate', as: :comparate
  get '/change_map/:id' => 'site#change_map', as: :change_map

  get '/update_vals' => 'site#update_vals', as: :update_vals

  get '/:page_title' => 'site#page', as: :page

  root :to => 'site#index'
end

app/controllers/site_controller.rb
# -*- encoding : utf-8 -*-

class SiteController < ApplicationController

  before_filter Proc.new {
    @editions = Edition.where(published: true).order('date ASC')

    @last_edition = @editions.last

    @penultimate_edition = @editions.order('date ASC').last(2).first

    unless @penultimate_edition.nil?
      @penultimate_edition_values = @penultimate_edition.values
    end

    @countries_ranking = Country.includes(:values).
      where('values.edition_id = ?', @last_edition.id).
        order('values.total DESC')

  }, except: [:graph, :general_graph, :change_map, :update_vals, :send_contact]

  def index
    @values = @last_edition.values.order('total DESC')
    @penultimate_countries_ranking = Country.includes(:values).
      where('values.edition_id = ?', @penultimate_edition.id).
        order('values.total DESC')
  end

  def ranking
    @editions.each do |e|
      @edition = e if e.name.parameterize('-') == params[:edition]
    end

    unless @edition.nil?
      @values = @edition.values.order('total DESC')

      if @editions.first != @edition
        @penultimate_countries_ranking = Country.includes(:values).
          where('values.edition_id = ?', @editions.index(@edition) - 1).
            order('values.total DESC')
      end
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def country
    @countries_ranking.each do |c|
      @country = c if c.name.parameterize('-') == params[:name]
    end

    unless @country.nil?
      @editions = Edition.includes(:values).order('date ASC')
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def comparate
    @countries_ranking.each do |c|
      @country1 = c if c.name.parameterize('-') == params[:name1]
    end

    @countries_ranking.each do |c|
      @country2 = c if c.name.parameterize('-') == params[:name2]
    end

    if @country1.nil? or @country2.nil?
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def page
    Page.where(published: true).each do |p|
      @page = p if p.title.parameterize == params[:page_title]
    end

    raise ActionController::RoutingError.new('Not Found') if @page.nil?

    @contact_form = Contact.new if ::Configuration.last.contact_page_id == @page.id
  end

  def graph
    @category = Category.find(params[:category])
    @country1 = Country.find(params[:country_1]) unless params[:country_1].nil?
    @country2 = Country.find(params[:country_2]) unless params[:country_2].nil?

    @editions = Edition.where(published: true).order('date ASC').
      includes(:values)

    respond_to do |format|
      format.js
    end
  end

  def general_graph
    @category = Category.find(params[:category])
    @editions = Edition.where(published: true).order('date ASC').
      includes(:values)

    respond_to do |format|
      format.js
    end
  end


  def change_map
    @edition = Edition.find(params[:id])
    @values = @edition.values.order('total DESC')

    respond_to do |format|
      format.js
    end
  end

  def update_vals
    Value.update_aux_values

    respond_to do |format|
      format.js
    end
  end

  # CONTACT BEGIN

  def send_contact
    @page = ::Configuration.last.contact_page
    @contact_form = Contact.new(params[:contact])

    if @contact_form.save
      redirect_to(page_path(@page.title.parameterize),
        notice: 'Mensagem enviada com sucesso.')
    else
      render action: :page
    end
  end

  # CONTACT END
end

app/views/site/_comparate_box.html.erb
<div class="qbox">
  <h3><i class="icon-search pull-right"></i>Compare os países</h3>

  <p>Faça uma comparação entre dois países e veja a diferenças
  de pontuação para cada uma dos componentes do Índice.</p>

  <hr />

  <div class="app-country-field">
    <select data-placeholder="Escolha um país" id="app-chzn-select-country1" style="width:100%;">
      <% @countries_ranking.each do |c| %>
      <option value="<%= c.name.parameterize %>"><%= c.name %></option>
      <% end %>
    </select>
  </div>

  <p style="text-align:center;" class="app-vs">Vs.</p>

  <div class="app-country-field">
    <select data-placeholder="Escolha um país" id="app-chzn-select-country2" style="width:100%;">
      <% @countries_ranking.each do |c| %>
        <option value="<%= c.name.parameterize %>" <%= 'selected="selected"'.html_safe if c.code == 'BR' %>>
          <%= c.name %>
        </option>
      <% end %>
    </select>
  </div>

  <%= link_to 'Comparar',
    comparate_path(@countries_ranking.first.name.parameterize, 'brasil'),
      class: 'btn btn-inverse btn-small btn-block', id: 'app-comparate-link' %>
</div>

<%= content_for :scripts do %>
  <script type="text/javascript">
    $(function () {
        var $select1 = $('#app-chzn-select-country1').select2();
        var $select2 = $('#app-chzn-select-country2').select2();

        <% if not @country.nil? %>
          $select1.select2('val', '<%= @country.name.parameterize %>')
        <% elsif not @country1.nil? %>
          $select1.select2('val', '<%= @country1.name.parameterize %>')
        <% end %>

        <% unless @country2.nil? %>
          $select2.select2('val', '<%= @country2.name.parameterize %>')
        <% end %>

        $select1.change(function (val) {
            $('#app-comparate-link').attr('href',
                '/comparar/' + val.val + '/' + $select2.select2('val'));
        });

        $select2.change(function (val) {
            $('#app-comparate-link').attr('href',
                '/comparar/' + $select1.select2('val') + '/' + val.val);
        });
    });
  </script>
<% end %>

app/views/site/_top_10_box.html.erb
<% unless @last_edition.nil? %>

  <%
    values = @last_edition.values.order('total DESC').limit(10)
    brazil = values.where(country_id: Country.where(code: 'BR').first).first
  %>

  <div class="qbox" id="app-top-10-box">
    <h3>Top 10 países mais livres e o Brasil</h3>

    <ul class="app-ranking">
      <% values.each.with_index do |v, i| %>

        <li class="app-elem row-fluid">
	        <div class="span2 app-pos"><span><%= i + 1 %>º</span></div>

	        <h4 class="span8"><%= link_to v.country.name,
	          country_path(v.country.name.parameterize) %></h4>

          <% unless v.total.nil? %>
	          <div class="span2 app-total">
	            <strong><%= v.total.round(2) %></strong>
	          </div>
	        <% end %>
        </li>

      <% end %>

      <% unless brazil.nil? %>
        <li class="app-elem row-fluid app-brazil">
	        <div class="span2 app-pos">
	          <%= @countries_ranking.index(brazil.country) + 1 %>º
	        </div>

	        <h4 class="span8"><%= link_to brazil.country.name,
	          country_path(brazil.country.name.parameterize) %></h4>

          <% unless brazil.total.nil? %>
	          <div class="span2 app-total">
	            <strong><%= brazil.total.round(2) %></strong>
	          </div>
	        <% end %>
        </li>
      <% end %>
    </ul>

  </div>

<% end %>

app/views/site/change_map.js.erb
var gdp_names = {
  <%= (@values.collect do |v|

    if v.country.code == 'DK'
      "'#{v.country.code}': '#{escape_javascript(v.country.name)}', 'GL': '#{escape_javascript(v.country.name)}'"
    elsif v.country.code == 'GB'
      "'#{v.country.code}': '#{escape_javascript(v.country.name)}', 'FK': '#{escape_javascript(v.country.name)}'"
    else
      "'#{v.country.code}': '#{escape_javascript(v.country.name)}'"
    end

  end * ',').html_safe %>
};

var gdp_data = {
  <%= (@values.where('total IS NOT NULL').collect do |v|

    if v.country.code == 'DK'
      "'#{v.country.code}': #{v.total}, 'GL': #{v.total}"
    elsif v.country.code == 'GB'
      "'#{v.country.code}': #{v.total}, 'FK': #{v.total}"
    else
      "'#{v.country.code}': #{v.total}"
    end

  end * ',').html_safe %>
};

$('#map').html('');

$(function () {
  $('#map').vectorMap({
      backgroundColor: 'transparent', zoomOnScroll: false,
      regionsSelectable: true, regionsSelectableOne: true,
      zoomStep: 1.2,
      series: {
        regions: [{
          values: gdp_data,
          scale: [
            '#ad0330',
            '#da7c38',
            '#CBE83C',
            '#5599ff',
            '#003d4f'
          ],
          normalizeFunction: function (data) {
            if      (data <= 10.0 && data >= 8.0) return 1;
            else if (data <   8.0 && data >= 7.0) return 0.75;
            else if (data <   7.0 && data >= 6.0) return 0.5;
            else if (data <   6.0 && data >= 5.0) return 0.25;
            else                                  return 0.0;

          },
          min: 0.0, max: 10.0
        }]
      },
      onRegionLabelShow: function(e, el, code){
        if (gdp_data[code] === undefined)
          el.html('Não há informações disponíveis');
        else
          el.html(gdp_names[code] + ' (' + gdp_data[code] + ')');
      },

      regionStyle: {
        initial: {
          fill: '#777',
          'fill-opacity': 1,
          stroke: 'none',
          'stroke-width': 0,
          'stroke-opacity': 1
        },
        hover: { 'fill-opacity': 0.8 },
        selected: { fill: '#444' }
      }
  });
});

$('#app-map-editions > li').removeClass('active');
$('#app-map-editions > li[data-id="<%= @edition.id %>"]').addClass('active');

app/views/site/contact.html.erb
<div id="main_content" class="contact_page">
  <%= content_tag(:p, notice, class: 'notice') if notice %>

  <%= simple_form_for(@contact_form, url: send_contact_path) do |f| %>
    <div class="inputs">
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :message, as: :text %>
    <div>

    <div class="actions">
      <%= f.button :submit, 'Enviar mensagem' %>
    </div>
  <% end %>
</div>

app/views/site/index.html.erb
<%= content_for :page_title do 'Principal' end %>
<%= content_for :page_id do 'home' end %>

<ul id="app-map-editions">
  <% @editions.each do |e| %>
    <li data-id="<%= e.id %>">
      <%= link_to e.name, change_map_path(e.id), remote: true %>
    </li>
  <% end %>
</ul>

<div id="map">
</div>

<div class="row-fluid" id="app-map-colors-degree">
  <p class="span6">Menos livres</p>
  <p class="span6">Mais livres</p>
</div>

<div class="body-text">

  <div class="container-fluid">

    <div class="row-fluid">

			<!--west pane span9-->
			<div class="span9">
				<div class="row-fluid">
					<h1>Os campeões de liberdade</h1>
				</div>

        <div class="row-fluid hotproperties">

          <% @values.limit(3).each.with_index do |v, i| %>
            <div class="span4 set-equal-heights-js freer">
              <div class="thumbnail">
                <%= link_to image_tag("/assets/cities/#{v.country.code.downcase}.png",
                  size: '221x150', class: 'thumbnail',
                  alt: v.country.name),
                  country_path(v.country.name.parameterize) %>

                <div class="caption">
                  <%= link_to v.country.name,
                    country_path(v.country.name.parameterize),
                    class: 'prop-title', title: v.country.name %>

								  <p class="app-home-ranking-detail">
                    <strong><%= i + 1 %>º</strong>
                    <strong>
                      <%= v.total.round(2) %><em>pontuação global</em>
                    </strong>

                    <%
                      old_val = @penultimate_edition_values.
                        where(country_id: v.country.id).first
                      old_pos = @penultimate_countries_ranking.index(v.country)

                      val_variation = v.total - old_val.total unless old_val.nil?
                      pos_variation = old_pos - i unless old_pos.nil?
                    %>

                    <strong>
                      <% unless val_variation.nil? %>
                        <% if val_variation < 0 %>
                          <i class="icon-chevron-down"></i>
                          <%= val_variation.round(2).abs %>
                        <% elsif val_variation > 0 %>
                          <i class="icon-chevron-up"></i>
                          <%= val_variation.round(2).abs %>
                        <% end %>
                      <% end %>
                      <br />
                      <% unless pos_variation.nil? %>
                        <% if pos_variation < 0 %>
                          <i class="icon-chevron-down"></i>
                          <%= pos_variation.abs %>
                        <% elsif pos_variation > 0 %>
                          <i class="icon-chevron-up"></i>
                          <%= pos_variation.abs %>
                        <% end %>
                      <% end %>
                    </strong>
								  </p>

                  <ul class="list-btns">
                    <li>
                      <a href="<%= country_path(v.country.name.parameterize) %>">
                        <i class="icon-info-sign"></i>Detalhes</a>
                    </li>
                  </ul>
							  </div>
              </div>
            </div>
          <% end %>

        </div>

			</div><!--end of west pane span9-->

			<!-- east pane with width of span3 -->
			<div class="span3">
			  <% unless configuration.freedom_val.blank? %>
			    <p id="app-freedom-value-box">
			      <strong>9.22</strong>
			      <span>é quão economicamente livre o mundo se encontra.</span>
			    </p>
			  <% end %>

		    <% unless @countries_ranking.empty? %>
          <%= render partial: 'comparate_box' %>
        <% end %>
			</div>
			<!-- end of span3 -->

		</div>
	</div>
</div>

<%= content_for :scripts do %>
  <script type="text/javascript">
    $('#app-map-editions > li:last a').click();
  </script>
<% end %>

app/views/site/page.html.erb
<%= content_for :page_title do @page.title end %>
<%= content_for :page_id do @page.id == configuration.contact_page_id ? 'contact' : 'page' end %>

<%= content_for :og do %>
  <%
    metas = [
      ['og:type',            'article'],
      ['og:title',           "Índice de Liberdade Econômica - #{@page.title}"],
      ['og:site_name',       'Índice de Liberdade Econômica'],
      ['og:description',     configuration.description],
      ['og:url',             request.url],
      ['og:image',           URI.join(root_url, '/assets/facebook_logo.png')],
      ['fb:app_id',          configuration.facebook_app_id]
    ]
  %>
  <% metas.each do |property, content| %>
    <meta property="<%= property %>" content="<%= content %>" />
  <% end %>
<% end %>

<div id="app-country-title">
  <h2><%= @page.title %></h2>
</div>

<div class="row-fluid">
  <div class="span9">
    <% if @page.content.present? or configuration.contact_page_id == @page.id %>
      <div class="app-page-content">
        <%= @page.content.html_safe %>

        <div class="form-wrapper">
          <% if configuration.contact_page_id == @page.id %>
            <%= content_tag(:p, notice,
              class: 'alert alert-success') if notice %>

            <%= simple_form_for(@contact_form, url: send_contact_path) do |f| %>
              <div class="form-fields">
                <%= f.input :name %>
                <%= f.input :email %>
                <%= f.input :message, as: :text %>
              </div>

              <div class="actions">
                <%= f.button :submit, 'Enviar mensagem', class: 'btn-peach' %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="span3">
    <%= render partial: 'top_10_box' %>

    <% unless @countries_ranking.nil? || @countries_ranking.empty? %>
      <%= render partial: 'comparate_box' %>
    <% end %>
  </div>
</div>

app/views/site/ranking.html.erb
<%= content_for :page_title do 'Ranking' end %>
<%= content_for :page_id do 'ranking' end %>

<%= content_for :og do %>
  <%
    metas = [
      ['og:type',            'article'],
      ['og:title',           "Índice de Liberdade Econômica - Ranking"],
      ['og:site_name',       'Índice de Liberdade Econômica'],
      ['og:description',     configuration.description],
      ['og:url',             request.url],
      ['og:image',           URI.join(root_url, '/assets/facebook_logo.png')],
      ['fb:app_id',          configuration.facebook_app_id]
    ]
  %>
  <% metas.each do |property, content| %>
    <meta property="<%= property %>" content="<%= content %>" />
  <% end %>
<% end %>

<% n = 0 %>

<div id="app-top-highlight">
  <%= render partial: 'comparate_box' %>
</div>

<div id="app-map-editions">
  <h3>Edições</h3>

  <ul>
    <% @editions.each do |e| %>
      <li data-id="<%= e.id %>" <%= 'class="active"'.html_safe if @edition == e %>>
        <%= link_to e.name, ranking_path(e.name.parameterize) %>
      </li>
    <% end %>
  </ul>
</div>

<div class="body-text">
  <h1 class="app-title">Ranking dos países</h1>

  <% free = @values.where('total <= 10.0 AND total >= 8.0') %>

  <h2 class="app-title free">
    <strong>Livres</strong>
    <em>(10 - 8)</em>
  </h2>

  <div class="app-ranking">
    <% free.each do |v| %>
      <%
        old_val = @penultimate_edition_values.where(country_id: v.country.id)

        unless @penultimate_countries_ranking.nil?
          old_pos = @penultimate_countries_ranking.index(v.country)
        end

        unless old_val.empty?
          old_val = old_val.first
          val_variation = v.total - old_val.total unless v.total.nil? && old_val.total.nil?
        end

        pos_variation = old_pos - n unless old_pos.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= n += 1 %>º</div>

	      <div class="span9">
		      <h3><%= link_to v.country.name,
		        country_path(v.country.name.parameterize) %></h3>

          <% unless v.total.nil? %>
		        <p>
		          <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

              <% unless val_variation.nil? %>
                <% if val_variation < 0 %>
                  <small>Variação no índice: <i class="icon-chevron-down"></i>
                  <%= val_variation.round(2).abs %></small>
                <% elsif val_variation > 0 %>
                  <small>Variação no índice: <i class="icon-chevron-up"></i>
                  <%= val_variation.round(2).abs %></small>
                <% end %>
              <% end %>

              <% unless pos_variation.nil? %>
                <% if pos_variation < 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-down"></i>
                  <%= pos_variation.abs %></small>
                <% elsif pos_variation > 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-up"></i>
                  <%= pos_variation.abs %></small>
                <% end %>
              <% end %>
		        </p>
		      <% else %>
            <p>Não há informações disponíveis</p>
		      <% end %>

	      </div>
      </div>
    <% end %>
  </div>

  <% mostly_free = @values.where('total < 8.0 AND total >= 7.0') %>

  <h2 class="app-title mostly-free">
    <strong>Majoritariamente livres</strong>
    <em>(7.9 - 7)</em>
  </h2>

  <div class="app-ranking">
    <% mostly_free.each do |v| %>
      <%
        old_val = @penultimate_edition_values.where(country_id: v.country.id)

        unless @penultimate_countries_ranking.nil?
          old_pos = @penultimate_countries_ranking.index(v.country)
        end

        unless old_val.empty?
          old_val = old_val.first
          val_variation = v.total - old_val.total unless v.total.nil? && old_val.total.nil?
        end

        pos_variation = old_pos - n unless old_pos.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= n += 1 %>º</div>

	      <div class="span9">
		      <h3><%= link_to v.country.name,
		        country_path(v.country.name.parameterize) %></h3>

          <% unless v.total.nil? %>
		        <p>
		          <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

              <% unless val_variation.nil? %>
                <% if val_variation < 0 %>
                  <small>Variação no índice: <i class="icon-chevron-down"></i>
                  <%= val_variation.round(2).abs %></small>
                <% elsif val_variation > 0 %>
                  <small>Variação no índice: <i class="icon-chevron-up"></i>
                  <%= val_variation.round(2).abs %></small>
                <% end %>
              <% end %>

              <% unless pos_variation.nil? %>
                <% if pos_variation < 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-down"></i>
                  <%= pos_variation.abs %></small>
                <% elsif pos_variation > 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-up"></i>
                  <%= pos_variation.abs %></small>
                <% end %>
              <% end %>
		        </p>
		      <% else %>
            <p>Não há informações disponíveis</p>
		      <% end %>

	      </div>
      </div>
    <% end %>
  </div>

  <% moderately_free = @values.where('total < 7.0 AND total >= 6.0') %>

  <h2 class="app-title moderately-free">
    <strong>Moderadamente livres</strong>
    <em>(6.9 - 6)</em>
  </h2>

  <div class="app-ranking">
    <% moderately_free.each do |v| %>
      <%
        old_val = @penultimate_edition_values.where(country_id: v.country.id)

        unless @penultimate_countries_ranking.nil?
          old_pos = @penultimate_countries_ranking.index(v.country)
        end

        unless old_val.empty?
          old_val = old_val.first
          val_variation = v.total - old_val.total unless v.total.nil? && old_val.total.nil?
        end

        pos_variation = old_pos - n unless old_pos.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= n += 1 %>º</div>

	      <div class="span9">
		      <h3><%= link_to v.country.name,
		        country_path(v.country.name.parameterize) %></h3>

          <% unless v.total.nil? %>
		        <p>
		          <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

              <% unless val_variation.nil? %>
                <% if val_variation < 0 %>
                  <small>Variação no índice: <i class="icon-chevron-down"></i>
                  <%= val_variation.round(2).abs %></small>
                <% elsif val_variation > 0 %>
                  <small>Variação no índice: <i class="icon-chevron-up"></i>
                  <%= val_variation.round(2).abs %></small>
                <% end %>
              <% end %>

              <% unless pos_variation.nil? %>
                <% if pos_variation < 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-down"></i>
                  <%= pos_variation.abs %></small>
                <% elsif pos_variation > 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-up"></i>
                  <%= pos_variation.abs %></small>
                <% end %>
              <% end %>
		        </p>
		      <% else %>
            <p>Não há informações disponíveis</p>
		      <% end %>

	      </div>
      </div>
    <% end %>
  </div>

  <% mostly_unfree = @values.where('total < 6.0 AND total >= 5.0') %>

  <h2 class="app-title mostly-unfree">
    <strong>Majoritariamente não livres</strong>
    <em>(5.9 - 5)</em>
  </h2>

  <div class="app-ranking">
    <% mostly_unfree.each do |v| %>
      <%
        old_val = @penultimate_edition_values.where(country_id: v.country.id)

        unless @penultimate_countries_ranking.nil?
          old_pos = @penultimate_countries_ranking.index(v.country)
        end

        unless old_val.empty?
          old_val = old_val.first
          val_variation = v.total - old_val.total unless v.total.nil? && old_val.total.nil?
        end

        pos_variation = old_pos - n unless old_pos.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= n += 1 %>º</div>

	      <div class="span9">
		      <h3><%= link_to v.country.name,
		        country_path(v.country.name.parameterize) %></h3>

          <% unless v.total.nil? %>
		        <p>
		          <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

              <% unless val_variation.nil? %>
                <% if val_variation < 0 %>
                  <small>Variação no índice: <i class="icon-chevron-down"></i>
                  <%= val_variation.round(2).abs %></small>
                <% elsif val_variation > 0 %>
                  <small>Variação no índice: <i class="icon-chevron-up"></i>
                  <%= val_variation.round(2).abs %></small>
                <% end %>
              <% end %>

              <% unless pos_variation.nil? %>
                <% if pos_variation < 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-down"></i>
                  <%= pos_variation.abs %></small>
                <% elsif pos_variation > 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-up"></i>
                  <%= pos_variation.abs %></small>
                <% end %>
              <% end %>
		        </p>
		      <% else %>
            <p>Não há informações disponíveis</p>
		      <% end %>

	      </div>
      </div>
    <% end %>
  </div>

  <% unfree = @values.where('total < 5 AND total >= 0.0') %>

  <h2 class="app-title unfree">
    <strong>Não livres</strong>
    <em>(4.9 - 0)</em>
  </h2>

  <div class="app-ranking">
    <% unfree.each do |v| %>
      <%
        old_val = @penultimate_edition_values.where(country_id: v.country.id)

        unless @penultimate_countries_ranking.nil?
          old_pos = @penultimate_countries_ranking.index(v.country)
        end

        unless old_val.empty?
          old_val = old_val.first
          val_variation = v.total - old_val.total unless v.total.nil? && old_val.total.nil?
        end

        pos_variation = old_pos - n unless old_pos.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= n += 1 %>º</div>

	      <div class="span9">
		      <h3><%= link_to v.country.name,
		        country_path(v.country.name.parameterize) %></h3>

          <% unless v.total.nil? %>
		        <p>
		          <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

              <% unless val_variation.nil? %>
                <% if val_variation < 0 %>
                  <small>Variação no índice: <i class="icon-chevron-down"></i>
                  <%= val_variation.round(2).abs %></small>
                <% elsif val_variation > 0 %>
                  <small>Variação no índice: <i class="icon-chevron-up"></i>
                  <%= val_variation.round(2).abs %></small>
                <% end %>
              <% end %>

              <% unless pos_variation.nil? %>
                <% if pos_variation < 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-down"></i>
                  <%= pos_variation.abs %></small>
                <% elsif pos_variation > 0 %>
                  <small>Variação no ranking: <i class="icon-chevron-up"></i>
                  <%= pos_variation.abs %></small>
                <% end %>
              <% end %>
		        </p>
		      <% else %>
            <p>Não há informações disponíveis</p>
		      <% end %>

	      </div>
      </div>
    <% end %>
  </div>

</div>