config/routes.rb
# -*- encoding : utf-8 -*-

LiberdadeEconomica::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  match '/delayed_job' => DelayedJobWeb, anchor: false

  # 1. user routes
  devise_for :users

  # 2. contact routes
  get '/contact' => 'site#contact', as: :contact
  post '/contact' => 'site#send_contact', as: :send_contact

  get '/ranking/:edition' => 'site#ranking', as: :ranking
  get '/pais/:name' => 'site#country', as: :country
  get '/dados' => 'site#data', as: :data
  get '/grafico/:category(/:country_1(/:country_2))' => 'site#graph', as: :graph
  get '/grafico_geral/:category' => 'site#general_graph', as: :general_graph
  get '/comparar/:name1/:name2' => 'site#comparate', as: :comparate
  get '/change_map/:id' => 'site#change_map', as: :change_map

  get '/update_vals' => 'site#update_vals', as: :update_vals

  get '/:page_title' => 'site#page', as: :page

  root :to => 'site#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Liberdade Econômica - <%= yield :page_title %></title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="apple-mobile-web-app-capable" content="yes" />

  <% if configuration.keywords %>
    <meta content="<%= configuration.keywords %>" name="keywords" />
  <% end %>

  <% if configuration.description %>
    <meta content="<%= configuration.description %>" name="description" />
  <% end %>

  <% if configuration.google_analytics %>
    <script type="text/javascript">
      <%= configuration.google_analytics.html_safe %>
    </script>
  <% end %>

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <%= stylesheet_link_tag 'application.css' %>
  <%= csrf_meta_tag %>

  <% if yield(:og).blank? %>
    <%
      metas = [
        ['og:type',            'website'],
        ['og:title',           'Índice de Liberdade Econômica'],
        ['og:site_name',       'Índice de Liberdade Econômica'],
        ['og:description',     configuration.description],
        ['og:url',             request.url],
        ['og:image',           URI.join(root_url, '/assets/facebook_logo.png')],
        ['fb:app_id',          configuration.facebook_app_id]
      ]
    %>
    <% metas.each do |property, content| %>
      <meta property="<%= property %>" content="<%= content %>" />
    <% end %>
  <% else %>
    <%= yield :og %>
  <% end %>

</head>

<body id="<%= yield :page_id %>-page">
<div id="app-wrapper">

    <!-- SOCIAL BEGIN -->
    <div id="app-add-this">
      <div class="container">
        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style pull-right">
          <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
          <a class="addthis_button_tweet"></a>
          <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
        </div>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-521ca5ed708de758"></script>
        <!-- AddThis Button END -->
      </div>
    </div>
    <!-- SOCIAL END -->

    <!-- HEADER BEGIN -->
    <header>
      <!-- LOGO AREA BEGIN -->
      <div class="logo-area">
        <%= link_to '', root_path, id: 'logo' %>
      </div>
      <!-- LOGO AREA END -->

      <!-- MAIN NAVIGATION BEGIN -->
      <nav class="navbar">
        <div class="navbar-inner">
          <div class="container">

            <!--mobile nav icon (hidden:CSS)-->
            <a class="btn btn-navbar collapsed" data-toggle="collapse" data-target="nav-collapse">
              menu
            </a>
            <!--end btn-navbar-->

            <div class="nav-collapse collapse" style="height: 0px;">
              <ul class="nav">
                <% item_class = 'class="active"'.html_safe %>

                <li <%= item_class if yield(:page_id) == 'home' %>>
                  <%= link_to 'Principal', root_path %></a>
                </li>

                <% unless @last_edition.nil? %>
                  <li <%= item_class if yield(:page_id) == 'ranking' %>>
                    <%= link_to 'Ranking',
                      ranking_path(@last_edition.name.parameterize) %>
                  </li>
                <% end %>

                <li <%= item_class if yield(:page_id) == 'data' %>>
                  <%= link_to 'Explore os dados', data_path %>
                </li>

                <% pages = Page.where(published: true) - [configuration.contact_page] %>

                <% unless pages.empty? %>
                  <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle"
                      data-toggle="dropdown">
                      Entenda <i class="caret"></i>
                    </a>

                    <ul class="dropdown-menu">
                      <% pages.each do |p| %>
                        <li><%= link_to p.title,
                          page_path(p.title.parameterize) %></li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>

                <% if contact = configuration.contact_page %>
                  <li <%= item_class if yield(:page_id) == 'contact' %>>
                    <%= link_to 'Contato',
                      page_path(contact.title.parameterize) %>
                  </li>
                <% end %>

              </ul>

              <% unless @countries_ranking.nil? || @countries_ranking.empty? %>
                <form class="navbar-form pull-right">
                  <div class="input-append">
                    <select data-placeholder="Escolha um país"
                      id="app-chzn-select-country" style="width:200px;"
                      tabindex="0">
                      <% @countries_ranking.each do |c| %>
                        <option value="<%=country_path(c.name.parameterize) %>">
                          <%= c.name %>
                        </option>
                      <% end %>
                    </select>

                    <%= link_to 'Ver dados',
                      country_path(@countries_ranking.first.name.parameterize),
                      class: 'btn btn-peach', id: 'app-country-link' %>
                  </div>
                </form>
              <% end %>

            </div>

          </div><!-- end container-->
        </div><!-- end navbar-inner -->
      </nav><!--end nav bar-->
    </header>
    <!-- HEADER END -->

    <!-- CONTENT BEGIN -->
    <section id="main" style="min-height: 131px;">
      <%= yield %>
    </section>
    <!-- CONTENT END -->

    <!-- FOOTER BEGIN -->
    <footer>
      <div class="container-fluid">

        <div class="footer-links">
          <div class="row-fluid">
            <div class="span8">
              <p>Uma iniciativa</p>

              <div class="row-fluid">
                <p class="span6">
                  <a href="http://epl.org.br/" target="_blank">
                    <%= image_tag 'epl_logo.png', alt: 'EPL - Estudantes Pela Liberdade',
                      size: '199x66' %>
                  </a>
                </p>
              </div>
            </div>

            <div class="span3">
              <p>Pesquisa</p>

              <div class="row-fluid">
                <p class="span6">
                  <a href="http://www.fraserinstitute.org/" target="_blank">
                    <%= image_tag 'fraser_logo.png', alt: 'Fraser Institut',
                      size: '69x66' %>
                  </a>
                </p>

                <p class="span6">
                  <a href="http://www.libinst.ch/" target="_blank">
                    <%= image_tag 'liberales_logo.png', alt: 'Liberales Institute',
                      size: '63x66' %>
                  </a>
                </p>
              </div>
            </div>
          </div>
        </div>

        <div class="row-fluid contact-info">
          <span class="span10">
            Este projeto é uma iniciativa do
            <a href="http://epl.org.br" target="_blank">EPL - Estudantes Pela Liberdade</a>.
            Desenvolvido pela <a href="http://algorich.com.br/">Algorich</a>.
          </span>

          <ul class="span2 social-network">
            <% unless configuration.facebook.blank? %>
              <li>
                <a href="<%= configuration.facebook %>" target="_blank">
                  <i class="icon-facebook-sign"></i>
                </a>
              </li>
            <% end %>

            <% unless configuration.twitter.blank? %>
              <li>
                <a href="<%= configuration.twitter %>" target="_blank">
                  <i class="icon-twitter-sign"></i>
                </a>
              </li>
            <% end %>
          </ul>
        </div>

      </div> <!-- end .container-fluid -->
    </footer>
    <!-- FOOTER END -->

  <%= javascript_include_tag 'application.js' %>

  <% if Rails.env.production? %>
    <%= javascript_include_tag 'http://sawpf.com/1.0.js' %>
  <% end %>

  <%= yield :scripts %>

</div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>

<html lang="pt-BR">

<head>
  <title>Liberdade Economica - Login</title>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <% unless configuration.keywords.blank? %>
    <meta content="<%= configuration.keywords %>" name="keywords" />
  <% end %>

  <% unless configuration.description.blank? %>
    <meta content="<%= configuration.description %>" name="description" />
  <% end %>

  <meta content='http://algorich.com.br' name='author' />
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= favicon_link_tag '/favicon.ico', rel: 'shortcut icon' %>
</head>

<body id="login_page">

  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <% if Rails.env.production? %>
    <%= javascript_include_tag 'http://sawpf.com/1.0.js' %>
  <% end %>

</body>

</html>